---
author: Nishibayashi Takuji
class: Module::Setup::Flavor::GitHub
email: 'takuji {at} senchan.jp'
github_format: p5-%s
githubmeta: 1
plugins:
  - Config::Basic
  - Template
  - Test::Makefile
  - Additional
  - VC::Git
  - Site::GitHub
readme_from: 0
readme_markdown_from: 0
readme_pod_from: 1
